Pop 68 Добавить любое WEB API (кроме Canvas и Fetch)
gitkh1/the-game pull request #12
Opened 2023-01-13 11:04 UTC by ZRNRD

### Добавлена страница настроек в основном меню

### Добавлено включение полноэкранного режима в настройках(Fullscreen API)

![Меню настроек](https://user-images.githubusercontent.com/74534888/212305062-ed1ab3a6-0cfb-464a-97a1-c88932b6c383.jpg)

2023-01-13 17:13 UTC, ftoh requested changes

2023-01-13 17:13 UTC, ftoh commented on packages/client/src/pages/MainMenuSettings/MainMenuSettings.tsx
> +    document.addEventListener('fullscreenchange', () => {
Этот код будет вызываться при каждом рендере. Надо поместить его в `useEffect`. И не забудь про отписку от событий.

2023-01-14 06:54 UTC, gitkh1 commented on package.json
> +    "node": ">=16"
Надо фиксировать версии

2023-01-14 09:37 UTC, ftoh commented on packages/client/src/pages/MainMenuSettings/MainMenuSettings.tsx
> +type T_WindowMode = string;
Я имел ввиду вот так, чтобы явно указать возможные варианты.
```
type T_WindowMode = 'Оконный' | 'Полноэкранный';
```

2023-01-14 09:42 UTC, ZRNRD commented on packages/client/src/pages/MainMenuSettings/MainMenuSettings.tsx
> +type T_WindowMode = string;
Ок, понял

2023-01-14 12:58 UTC, ftoh approved these changes

2023-01-16 16:25 UTC, RodionBozhenko commented on packages/client/src/pages/MainMenuSettings/MainMenuSettings.tsx
> +type T_WindowMode = 'Оконный' | 'Полноэкранный';
Типы как и любой другой код лучше называть на инглише

2023-01-16 16:36 UTC, RodionBozhenko commented on packages/client/src/pages/MainMenuSettings/MainMenuSettings.tsx
> +        if (!document.fullscreenElement) {
Вот такие переменные, которые используются неоднократно лучше выносить в переменную в начале компонента, для удобочитаемости и легком дебаге кода. То есть const isFullScreenModeUsed = document.fullScreenElement

2023-01-16 16:38 UTC, RodionBozhenko approved these changes
Все замечательно. Оставил небольшие комменты, на функционал это никак не влияет, но в плане чистого кода, к которому миддлам надо стремиться, предлагаю их рассмотреть и в дальнейшем использовать

2023-01-17 06:42 UTC, merged