Добавляет API страницы пользователя
gitkh1/the-game pull request #15
Opened 2023-01-16 05:00 UTC by gitkh1

### Какую задачу решаем
Добавлено api для страниц пользователя
Отредактированы реализации api методов

Прошу прощения, забыл сделать отдельную ветку, сделал все в этой:
- Отредактированы страницы под общий стиль экспорта и импорта (через index)
- В роутере перенесены все страницы в общий объект с путями.

### Что осталось
Обработка форм через `react-hook-form` идет костыльно: не нашел способа через эту либу отправлять formData с аватаром; не выставляются defaultValue у инпутов после редндера компонентов.
Данные пользователя пока что подгружаются на каждой странице - ждем редакс, чтобы хранить данные в приложении.

2023-01-20 11:42 UTC, RodionBozhenko commented on packages/client/src/game/runGame.ts
> +    const time = shakeTime > SHAKE_TIME_FRAMES / 2 ? SHAKE_TIME_FRAMES - shakeTime : shakeTime;
Условие shakeTime > SHAKE_TIME_FRAMES / 2 лучше вынести в отдельную переменную, которая своим названием объяснит суть условия. Таким образом, улучшишь читаемость кода

2023-01-20 11:47 UTC, RodionBozhenko commented on packages/client/src/modules/formBuilder/components/FieldBuilder/FieldBuilder.tsx
> +  }, [defaultValue]);
Этот эффект меняет значение в зависимости от дефолтного значения. В этом нет нужды, так как дефолтное значение указано при вызове useState и defaultValue есть в пропсах. Компонент зависит от пропсов, соответственно при изменении значения по дефолту в пропсах компонент уже будет обладать необходимым значением.

2023-01-20 11:50 UTC, RodionBozhenko commented on packages/client/src/modules/formBuilder/components/FormBuilder/FormBuilder.tsx
> +            value={values && values.avatar || ''} />
Тут можно использовать optional chaining. Т. е. вместо values && values.avatar || '' сделать values?.avatar || ''. Работать будет точно также, но код станет чуть лаконичнее

2023-01-20 11:57 UTC, RodionBozhenko commented on packages/client/src/modules/formBuilder/components/FormBuilder/FormBuilder.tsx
> +            </Button>}
Вот таким условиям лучше предпочитать тернарный оператор. Таким образом код будет выглядеть так - structure.submit?.title ? <Компонент> : null. Это поможет избежать непредвиденных багов. Ссылки с объяснениями - https://stackoverflow.com/questions/70107879/when-to-use-ternary-operator-over-the-logical-operator-in-react-to-render-condit https://stackoverflow.com/questions/65713434/react-render-logical-vs-ternary-operator

2023-01-20 11:58 UTC, RodionBozhenko commented on packages/client/src/modules/formBuilder/components/LabledFiledInput/LabledFiledInput.tsx
> +  }, [value]);
Об этом уже писал выше

2023-01-20 12:01 UTC, RodionBozhenko commented on packages/client/src/modules/formBuilder/components/LabledFiledInput/LabledFiledInput.tsx
> +    if (!(e && e.target && e.target.files && e.target.files[0])) {
Это опять же можно все заменить на optional chaining. Получится вот такое условие if (!e?.target?.files[0]). И еще лучше если это условие вынести в переменную. Например, const fileNotPassed = !e?.target?.files[0]. Таким образом, получается лаконичное и понятное условие if (fileNotPassed) return

2023-01-20 12:05 UTC, RodionBozhenko commented on packages/client/src/pages/Profile/Profile.tsx
Тут вместо того, чтобы "насильно" типизировать response с помощью as, лучше указать его дженериков в функции getInfo(). authApi.getInfo<T_UserInfoData>(). И тайпскрипт не будет ругаться

2023-01-20 12:13 UTC, RodionBozhenko requested changes
В целом все здорово. Вижу, что проделана большая работа. Оставил комменты, где надо пофиксить, опять же там ничего значительного. Но я вижу, что ты используешь react-hook-form не так как следовало бы. Это библиотека пропагандирует использование неконтролируемых инпутов. Это сделано целенаправленно и у этого подхода есть твердая основа. Например, в сравнение с formik, который использует контролируемые инпуты, в RHF намного меньше перерендеров компонент. Если использование контролируемых инпутов сделано специально и, возможно, такова была задача, дай знать, если же нет, то предлагаю ознакомиться с документацией react-hook-form https://react-hook-form.com/get-started.  У них документация вполне неплохо объясняет принцип работы библиотеки и ее философию.

2023-01-20 14:14 UTC, gitkh1 commented on packages/client/src/game/runGame.ts
> +    const time = shakeTime > SHAKE_TIME_FRAMES / 2 ? SHAKE_TIME_FRAMES - shakeTime : shakeTime;
Поправил

2023-01-20 14:15 UTC, gitkh1 commented on packages/client/src/modules/formBuilder/components/FieldBuilder/FieldBuilder.tsx
> +  }, [defaultValue]);
Согласен, убрал.

2023-01-20 14:15 UTC, gitkh1 commented on packages/client/src/modules/formBuilder/components/FormBuilder/FormBuilder.tsx
> +            value={values && values.avatar || ''} />
Исправил

2023-01-20 14:15 UTC, gitkh1 commented on packages/client/src/modules/formBuilder/components/FormBuilder/FormBuilder.tsx
> +            </Button>}
Спасибо, исправил

2023-01-20 14:16 UTC, gitkh1 commented on packages/client/src/modules/formBuilder/components/LabledFiledInput/LabledFiledInput.tsx
> +  }, [value]);
Исправил

2023-01-20 14:17 UTC, gitkh1 commented on packages/client/src/pages/Profile/Profile.tsx
Исправил

2023-01-20 14:24 UTC, gitkh1 commented
> В целом все здорово. Вижу, что проделана большая работа. Оставил комменты, где надо пофиксить, опять же там ничего значительного. Но я вижу, что ты используешь react-hook-form не так как следовало бы. Это библиотека пропагандирует использование неконтролируемых инпутов. Это сделано целенаправленно и у этого подхода есть твердая основа. Например, в сравнение с formik, который использует контролируемые инпуты, в RHF намного меньше перерендеров компонент. Если использование контролируемых инпутов сделано специально и, возможно, такова была задача, дай знать, если же нет, то предлагаю ознакомиться с документацией react-hook-form https://react-hook-form.com/get-started. У них документация вполне неплохо объясняет принцип работы библиотеки и ее философию.

Спасибо за ревью.
Согласен про RHF.
У меня возникала такая ошибка [https://github.com/preactjs/preact/issues/2954](https://github.com/preactjs/preact/issues/2954) элемент TextField из MUI не обновлял defaultValue после обновления пропсов. Например, value или placeholder обновлялись по поступлению новых пропсов, а defaultValue не обновлялись.
Еще пример, если брать обычный <input /> элемент, то все в порядке и он обновляется при изменении пропсов. Но обычный инпут не подходит.
Сейчас сделал менее костыльно: при изменении пропса defaultValue вешаю через ref на input поле новое значение поля value

2023-01-22 14:17 UTC, RodionBozhenko approved these changes
Отлично

2023-01-23 03:17 UTC, merged