Pop 49 подружить redux и ssr
gitkh1/the-game pull request #29
Opened 2023-02-13 08:06 UTC by Anatoly2403

### Какую задачу решаем
Подружить Redux и SSR

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-13 13:21 UTC, ftoh requested changes
В `yarn dev:server` очень долго обрабатывается запрос. Экспериментальным путём нашёл, что причина в
`packages\client\src\pages\LeaderBoard\LeaderBoard.tsx`
```diff
- import { KeyboardArrowLeft, KeyboardArrowRight } from "@mui/icons-material";
+ import KeyboardArrowLeft from "@mui/icons-material/KeyboardArrowLeft";
+ import KeyboardArrowRight from "@mui/icons-material/KeyboardArrowRight";
```

При запуске приложения через `yarn dev:client` или `yarn dev:server` перестали работать запросы к API. Функция, которую передаём в `createAsyncThunk`, просто не вызывается. Из-за этого в разделах «Профиль» и «Таблица лидеров» пусто.

2023-02-13 13:21 UTC, ftoh commented on packages/server/index.ts
>          render = (await import(ssrClientPath)).render;
Здесь то же можно вынести в переменную.

2023-02-13 17:07 UTC, Anatoly2403 commented on packages/server/index.ts
>          render = (await vite!.ssrLoadModule(path.resolve(srcPath, "ssr.tsx") as string)).render;
+

2023-02-13 17:07 UTC, Anatoly2403 commented on packages/server/index.ts
>          render = (await import(ssrClientPath)).render;
+

2023-02-13 17:07 UTC, Anatoly2403 commented on packages/server/index.ts
> +import type { T_CreateStore, T_Store } from "client/src/global/store";
+ перестали работать запросы к API. Починил)

2023-02-13 23:55 UTC, gitkh1 commented on packages/client/src/api/Api.ts
> -  public async putFile(endPoint: string, data?: FormData): Promise<XMLHttpRequest> {
Я думаю, этот метод удалять нельзя. Он отправляет аватар как FormData. 
Или переделать метод fetchMethod, потому что он делает stringify любого типа данных.

2023-02-14 00:37 UTC, Anatoly2403 commented on packages/client/src/api/Api.ts
> -  public async putFile(endPoint: string, data?: FormData): Promise<XMLHttpRequest> {
поправил

2023-02-14 09:44 UTC, ftoh commented on packages/client/src/pages/ProfileChangeData/ProfileChangeData.tsx
> +      if (avatar) {
Это условие всегда true, и в строке `formData.append("avatar", avatar, avatar.name);` вылетает ошибка из-за неправильного типа
![image](https://user-images.githubusercontent.com/5018813/218696384-ea3a3480-30bc-4ef7-8a92-d41c8d86dfbf.png)

Если у пользователя нет аватара, то при сохранении в avatar лежит тип `FileList`.
Если был указан, но не менять, то — `string`.
Если изменить аватар, то там будет тип `File`

![image](https://user-images.githubusercontent.com/5018813/218695889-bfedd74e-db5f-42f2-8b59-07915fda1114.png)
![image](https://user-images.githubusercontent.com/5018813/218697362-2e84faeb-9467-455a-8b90-41ac5a606269.png)

2023-02-14 10:52 UTC, Anatoly2403 commented on packages/client/src/pages/ProfileChangeData/ProfileChangeData.tsx
> +      if (avatar) {
Поправил

2023-02-14 11:09 UTC, ftoh approved these changes

2023-02-14 13:34 UTC, gitkh1 approved these changes

2023-02-15 21:29 UTC, RodionBozhenko approved these changes
👍

2023-02-16 12:07 UTC, merged