POP-89 Сбор обратной связи
gitkh1/the-game pull request #34
Opened 2023-02-22 12:04 UTC by Anatoly2403

### Какую задачу решаем
Сбор обратной связи

### Скриншоты/видяшка (если есть)
![image](https://user-images.githubusercontent.com/65222585/220614801-03f51912-c403-4a2e-8496-2289513e776b.png)

2023-02-24 08:59 UTC, gitkh1 commented on packages/client/src/components/Feedback/Feedback.tsx
> +/* eslint-disable @typescript-eslint/no-unsafe-assignment */
Вот это все можно убрать, ниже напишу

2023-02-24 08:59 UTC, gitkh1 commented on packages/client/src/components/Feedback/Feedback.tsx
> +      if (field === FORM_FIELDS.LOGIN || field === FORM_FIELDS.EMAIL) {
` if ((field === FORM_FIELDS.LOGIN || field === FORM_FIELDS.EMAIL) && (data) && (field in data)) {`
можно так, например

2023-02-24 09:00 UTC, gitkh1 commented on packages/client/src/components/Feedback/Feedback.tsx
> +import React, { FC, useState } from "react";
Можно убрать React
`import { FC, useState } from "react";`

2023-02-24 09:00 UTC, gitkh1 commented on packages/client/src/components/Feedback/Feedback.tsx
> +              onSubmit={(data) => handleSubmit(data)}
` onSubmit={(data) => void handleSubmit(data)}`
можно так

2023-02-24 09:04 UTC, gitkh1 commented on packages/client/src/components/Feedback/Feedback.tsx
> +      {!userInfo && null}
не понял, зачем это условие

2023-02-24 09:05 UTC, gitkh1 commented on packages/client/src/components/Feedback/Feedback.tsx
> +      {userInfo && (
Про && говорили в этом же проекте, что желательно делать тернаркой, чтобы не было багов
`a === b ? 
                something
               : null`

2023-02-24 09:12 UTC, gitkh1 commented on packages/client/src/components/Feedback/Feedback.tsx
> +            })}
Здесь не знаю, наверное, можно типизировать `styles` 
или написать только для этой строки
 `// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call`

2023-02-24 09:42 UTC, gitkh1 commented on packages/client/src/components/Notification/Notification.tsx
> +import React, { FC, PropsWithChildren, useEffect, useMemo } from "react";
React можно не импортировать

2023-02-24 09:46 UTC, gitkh1 commented on packages/client/src/global/store/index.ts
> +/* eslint-disable @typescript-eslint/no-unsafe-member-access */
Предлагаю это писать над конкретной строкой, чтобы не делать исключение для всего файла

2023-02-24 09:46 UTC, gitkh1 commented on packages/client/src/game/Game.tsx
> +/* eslint-disable @typescript-eslint/no-unsafe-member-access */
Предлагаю это писать над конкретной строкой, чтобы не делать исключение для всего файла

2023-02-24 09:47 UTC, gitkh1 commented on packages/client/src/global/store/slices/notification.ts
> +/* eslint-disable @typescript-eslint/no-unsafe-assignment */
Это вроде можно убрать

2023-02-24 09:51 UTC, gitkh1 commented on packages/client/src/pages/Profile/Profile.tsx
> +/* eslint-disable @typescript-eslint/no-unsafe-call */
Вроде тоже можно убрать, я пробовал

2023-02-24 09:55 UTC, gitkh1 commented on packages/server/routes/feedbackRoute.ts
> +/* eslint-disable @typescript-eslint/unbound-method */
Эти eslint, скорее всего, потому что feedbackController не достаточно типизирован

2023-02-24 09:55 UTC, gitkh1 commented on packages/server/package.json
> +    "node-telegram-bot-api": "^0.61.0",
Надо зафиксировать

2023-02-24 09:56 UTC, gitkh1 commented on packages/server/controllers/feedbackController.ts
> +/* eslint-disable @typescript-eslint/no-unsafe-assignment */
Это можно попробовать убрать)

2023-02-24 09:56 UTC, gitkh1 commented on packages/server/controllers/feedbackController.ts
> +      res.json({ email: record.email, login: record.login, feedback: record.feedback });
А здесь через опциональную цепочку, наверное `record?.login` ...

2023-02-24 09:57 UTC, gitkh1 requested changes
Ты, наверное, тегни остальных в ревью реквкестах, у них, возможно, не видно)

2023-02-24 13:20 UTC, gitkh1 approved these changes

2023-02-26 17:01 UTC, RodionBozhenko approved these changes

2023-02-27 03:23 UTC, ftoh approved these changes

2023-02-27 03:36 UTC, merged